### ISSUE TITLE
Armstrong number: JAVA prints only for a three digit number

### ISSUE THREAD

**Issue by dubey0613** [SAMYAK99/CS-180#524]
Hey, the program https://github.com/SAMYAK99/CS-180.git (Armstrong number: JAVA) checks the number for a three digit Armstrong number only. I have a better code which checks for any digit number.
Can I contribute to it?

**Comment by SAMYAK99** [comment]
Sure

**Comment by dubey0613** [comment]
> Sure

I've created a pull request, kindly review it.
