### ISSUE TITLE
flex panels website

### ISSUE THREAD

**Issue by shivamsisodia07** [SAMYAK99/CS-180#596]
![Screenshot (1)](https://user-images.githubusercontent.com/88767597/194723427-348399be-f478-4dc4-8365-c37ce570f1a0.png)
![Screenshot (2)](https://user-images.githubusercontent.com/88767597/194723432-22e2cf0a-eb39-46bb-b477-646bbf6b7f2f.png)

**Comment by shivamsisodia07** [comment]
I would like to contribute . hacktoberfest 2022

**Comment by SAMYAK99** [comment]
sure
