### ISSUE TITLE
Add a file in c, which shows a multiplication table .

### ISSUE THREAD

**Issue by rishabh1911007** [SAMYAK99/CS-180#760]
Could you please assign me for this issue.

**Comment by rishabh1911007** [comment]
#Hacktoberfest2022

**Comment by keshavsolankii** [comment]
Sir, can you assign me this issue?

**Comment by silky-modi22** [comment]
can you please assign this issue to me!

**Comment by silky-modi22** [comment]
Why you closed my pr . What you exactly want . Please mention it I'll try
to add it.

**Comment by silky-modi22** [comment]
Ok, it's fine because it is the issue is solved.
