### ISSUE TITLE
Make Temperature Converter with Java

### ISSUE THREAD

**Issue by rishabh1911007** [SAMYAK99/CS-180#767]
Could you please assign me for this issue.

**Comment by rishabh1911007** [comment]
#Hacktoberfest2022

**Comment by pritam1309** [comment]
can you assign it to me with prober labels

**Comment by pritam1309** [comment]
Plz merge it with proper labels

**Comment by keshavsolankii** [comment]
Sir, please assign me this issue.

**Comment by SAMYAK99** [comment]
@pritam1309 Include PR with this issue
